name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['stable', 'nightly']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.1"
      
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v6
      
      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luacov
          luarocks install luacheck
      
      - name: Run linter
        run: |
          luacheck lua/ --globals vim
      
      - name: Run tests
        run: |
          busted --verbose --coverage
      
      - name: Generate coverage report
        run: |
          luacov -r html
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./luacov.report.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.1"
      
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v6
      
      - name: Install luacheck
        run: luarocks install luacheck
      
      - name: Run luacheck
        run: luacheck lua/ --globals vim

  stylua:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/