name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'lua/**'
      - 'doc/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'lua/**'
      - 'doc/**'
      - '.github/workflows/docs.yml'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.1"
      
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v5
      
      - name: Install dependencies
        run: |
          luarocks install --local ldoc
          luarocks install --local --lua-version 5.1 mini.doc
      
      - name: Generate user documentation
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: screw.nvim
          version: "0.9.0"
          demojify: true
          treesitter: true
      
      - name: Generate API documentation
        run: |
          eval $(luarocks path --lua-version 5.1 --bin)
          make api-documentation
      
      - name: Generate vim help tags
        run: |
          nvim --headless -c 'helptags doc' -c 'quit'
      
      - name: Clean up unwanted files
        run: |
          # Remove the minimal screw.txt file generated by mini.doc (we use screw.nvim.txt)
          if [ -f doc/screw.txt ] && [ $(wc -l < doc/screw.txt) -lt 3 ]; then
            echo "Removing minimal screw.txt file generated by mini.doc"
            rm doc/screw.txt
          fi
      
      - name: Commit documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add doc/
          git diff --staged --quiet || git commit -m "docs: auto-generated documentation [skip ci]"
          git push