name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'lua/**'
      - 'doc/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'lua/**'
      - 'doc/**'
      - '.github/workflows/docs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1"
      
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v5
      
      - name: Install dependencies
        run: |
          luarocks install --local ldoc
      
      - name: Generate vim documentation
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: screw.nvim
          version: "0.9.0"
          demojify: true
          treesitter: true
      
      - name: Commit documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add doc/
          git diff --staged --quiet || git commit -m "docs: auto-generated documentation [skip ci]"
          git push